# Generated by Django 3.0.3 on 2020-03-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ingresso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='ingresso',
            new_name='ingressos',
        ),
    ]
