# Generated by Django 3.0.3 on 2020-03-13 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ingresso', '0002_auto_20200313_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.Evento', verbose_name='Evento'),
        ),
    ]
